import bcrypt from "bcryptjs";
export const DATA = {
  users: [
    {
      name: "Gabriel",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("admin"),
      isAdmin: true,
    },
    {
      name: "Ronaldo",
      email: "standbyg2@gmail.com",
      password: bcrypt.hashSync("gabriel"),
      isAdmin: false,
    },
  ],
  category: [
    {
      //_id: 1,
      title: "Hombre",
      image: "/images/category/men1.jpg",
    },
    {
      //_id: 2,
      title: "Mujeres",
      image: "/images/category/woman.jpg",
    },
    {
      //_id: 3,
      title: "Niños",
      image: "/images/category/child1.jpg",
    },
  ],
  Products: [
    {
      //_id: 1,
      title: "Product 1",
      slug: "product1",
      desc: "Description for product 1",
      category: "Hombre",
      image: "/images/products/hombre1.webp",
      image1: "/images/products/hombre1.webp",
      image2: "/images/products/hombre1.webp",
      image3: "/images/products/hombre1.webp",
      countInStock: 5,
      price: "80.00",
    },
    {
      //_id: 2,
      title: "Product 2",
      slug: "product2",
      desc: "Polera hecha a base de tela",
      category: "Mujeres",
      image: "/images/products/mujer1.webp",
      image1: "/images/products/mujer1.webp",
      image2: "/images/products/mujer1.webp",
      image3: "/images/products/mujer1.webp",
      countInStock: 5,
      price: "100.00",
    },
    {
      //_id: 3,
      title: "Product 3",
      slug: "product3",
      desc: "Description for product 3",
      category: "Niños",
      image: "/images/products/nino1.webp",
      image1: "/images/products/nino1.webp",
      image2: "/images/products/nino1.webp",
      image3: "/images/products/nino1.webp",
      countInStock: 5,
      price: "90.00",
    },
    {
      //_id: 4,
      title: "Product 4",
      slug: "product4",
      desc: "Description for product 4",
      category: "Mujeres",
      image: "/images/products/mujer2.webp",
      image1: "/images/products/mujer2.webp",
      image2: "/images/products/mujer2.webp",
      image3: "/images/products/mujer2.webp",
      countInStock: 5,
      price: "120.00",
    },
    {
      //_id: 5,
      title: "Product 5",
      slug: "product5",
      desc: "Description for product 1",
      category: "Hombre",
      image: "/images/products/hombre1.webp",
      image1: "/images/products/hombre1.webp",
      image2: "/images/products/hombre1.webp",
      image3: "/images/products/hombre1.webp",
      countInStock: 5,
      price: "100.00",
    },
    {
      //_id: 6,
      title: "Product 6",
      slug: "product6",
      desc: "Description for product 1",
      category: "Hombre",
      image: "/images/products/hombre1.webp",
      image1: "/images/products/hombre1.webp",
      image2: "/images/products/hombre1.webp",
      image3: "/images/products/hombre1.webp ",
      countInStock: 5,
      price: "180.00",
    },
    {
      //_id: 6,
      title: "Product 7",
      slug: "product7",
      desc: "Description for product 7",
      category: "Hombre",
      image: "/images/products/polohombrewebp.webp",
      image1: "/images/products/polohombrewebp.webp",
      image2: "/images/products/polohombrewebp.webp",
      image3: "/images/products/polohombrewebp.webp ",
      countInStock: 5,
      price: "190.00",
    },
  ],
};
